---
- name: Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: "0755"

- name: Symlink starship.toml
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/starship/starship.toml"
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    state: link
    force: true
