---
- name: Install tmux (apt)
  become: true
  ansible.builtin.apt:
    name: tmux
    state: present
  when: ansible_os_family == "Debian"

- name: Install tmux (homebrew)
  community.general.homebrew:
    name: tmux
    state: present
  when: ansible_os_family == "Darwin"

- name: Symlink tmux.conf
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/config/tmux/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    state: link
    force: true
