---
- name: Install vim (apt)
  become: true
  ansible.builtin.apt:
    name: vim
    state: present
  when: ansible_os_family == "Debian"

- name: Install vim (homebrew)
  community.general.homebrew:
    name: vim
    state: present
  when: ansible_os_family == "Darwin"

- name: Symlink vimrc
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/config/vim/.vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    state: link
    force: true
