---
- name: Install sublime-text (snap)
  become: true
  community.general.snap:
    name: sublime-text
    classic: true
    state: present
  when: ansible_os_family == "Debian"

- name: Install sublime-text (homebrew cask)
  community.general.homebrew_cask:
    name: sublime-text
    state: present
  when: ansible_os_family == "Darwin"

- name: Ensure sublime-text Packages directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/sublime-text/Packages"
    state: directory
    mode: "0755"

- name: Check if User directory exists and is not a symlink
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.config/sublime-text/Packages/User"
  register: sublime_user

- name: Remove existing User directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/sublime-text/Packages/User"
    state: absent
  when:
    - sublime_user.stat.exists
    - not sublime_user.stat.islnk

- name: Symlink sublime User config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/subl/User"
    dest: "{{ ansible_env.HOME }}/.config/sublime-text/Packages/User"
    state: link
    force: true
